env:
  node: true
  jest: true
plugins:
  - jest
extends:
  - 'eslint:recommended'
  - 'standard'
parserOptions:
  ecmaVersion: 8
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
